version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/my-item-stock-front
permissions:
  - object: /home/ec2-user/my-item-stock-front
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
